name: 'finance_project'
version: '1.0.0'
config-version: 2

profile: 'finance_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finance_project:
    +materialized: view
