ignore:
  - "cosmos/airflow/_override.py"

coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 2%
        only_pulls: true
    project:
      default:
        target: auto
        threshold: 0.5%
        removed_code_behavior: fully_covered_patch
