default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: 4

postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      dbname: postgres #'{{ env_var(''POSTGRES_DATABASE'') }}'
      host: "0.0.0.0" #'{{ env_var(''POSTGRES_HOST'') }}'
      pass: postgres #'{{ env_var(''POSTGRES_PASSWORD'') }}'
      port: 5432 #'{{ env_var(''POSTGRES_PORT'') | as_number }}'
      schema: postgres # '{{ env_var(''POSTGRES_SCHEMA'') }}'
      user: "postgres" #'{{ env_var(''POSTGRES_USER'') }}'
