default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: 4

postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      dbname: "{{ env_var('POSTGRES_DATABASE') }}"
      host: "{{ env_var('POSTGRES_HOST') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432 # "{{ env_var('POSTGRES_PORT') | as_number }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      user: "{{ env_var('POSTGRES_USER') }}"

bigquery_dev:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: astronomer-dag-authoring
      dataset: bq_dev
      threads: 4 # Must be a value of 1 or greater
      keyfile: /usr/local/airflow/include/key.json
      location: US

bigquery_clone:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: astronomer-dag-authoring
      dataset: bq_clone
      threads: 4 # Must be a value of 1 or greater
      keyfile: /usr/local/airflow/include/key.json
      location: US
