default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost # "{{ env_var('POSTGRES_HOST') }}"
      user: postgres # "{{ env_var('POSTGRES_USER') }}"
      password: postgres # "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432 # "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: airflow_db1 # "{{ env_var('POSTGRES_DB') }}"
      schema: public # "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: 4

postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost # "{{ env_var('POSTGRES_HOST') }}"
      user: postgres # "{{ env_var('POSTGRES_USER') }}"
      password: postgres # "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432 # "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: airflow_db1 # "{{ env_var('POSTGRES_DB') }}"
      schema: public # "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: 4
