# WARNING: this gets ignored by cosmos
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: public
      schema: dbt_example
      threads: 4
