FROM python:3.12

RUN pip install --force-reinstall 'dbt-postgres>=1.8'
RUN pip install --force-reinstall dbt-adapters

ENV POSTGRES_DATABASE=postgres
ENV POSTGRES_DB=postgres
ENV POSTGRES_HOST=postgres.default.svc.cluster.local
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_PORT=5432
ENV POSTGRES_SCHEMA=public
ENV POSTGRES_USER=postgres

RUN mkdir /root/.dbt
COPY dags/dbt/jaffle_shop/profiles.yml /root/.dbt/profiles.yml

RUN mkdir dags
COPY dags dags
RUN rm dags/dbt/jaffle_shop/packages.yml
