version: 2

models:
  - name: attribution_touches
    description: One record per web session prior to conversion AND within the last 30 days.

    columns:
      - name: session_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: total_sessions
        description: The total sessions prior to conversion AND within the last 30 days.
        tests:
          - not_null

      - name: session_index
        description: The relative position of this session
        tests:
          - not_null