name: 'platform_project'
version: '1.0.0'
config-version: 2

profile: 'platform_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  platform_project:
    staging:
      +materialized: view
      +access: public
