
version: 2

sources:
  - name: postgres_db
    database: "{{ env_var('POSTGRES_DB') }}"
    schema: "{{ env_var('POSTGRES_SCHEMA') }}"
    tables:
      - name: raw_customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: raw_payments
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: raw_orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
        freshness:
          warn_after:
            count: 3650
            period: day
        loaded_at_field: CAST(order_date AS TIMESTAMP)
