manifests:
  - name: project_a
    type: file
    config:
      # Use environment variable for flexibility, with fallback to relative path
      # path: '{{ env_var("PROJECT_A_MANIFEST_PATH", "../project_a_bidirectional/target/manifest.json") }}'

      # For GitHub Actions Integration Tests CI run, set the path to the manifest.json file
      path: /home/runner/work/astronomer-cosmos/astronomer-cosmos/dev/dags/dbt/cross_project/project_a_bidirectional/target/manifest.json
enable_telemetry: false
