name: 'dbt_loom_downstream_finance'
version: '1.0.0'
config-version: 2

profile: 'dbt_loom_downstream_finance'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dbt_loom_downstream_finance:
    # Fact tables - materialized as tables for performance
    +materialized: table
    # Reports can be views
    rpt_revenue_summary:
      +materialized: view
