name: Kubernetes Integration Tests

on: push

jobs:
  run-kubernets-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
      - name: Run tests
        run: |
          sh ./scripts/test/kubernetes-setup.sh
          pip install hatch
          hatch -e tests.py3.9-2.9 run pip freeze
          hatch run tests.py3.9-2.9:test-kubernetes
          kubectl get pods -o wide
          kubectl logs postgres-postgresql-0
